=== ManeStepanyan/MobileStore/CatalogAPI/MapInfo/MapSchema.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="operations">
    <xs:complexType>
      <xs:sequence>

        <!--operation-->
        <xs:element name="operation" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              
              <!--stored procedure name-->
              <xs:element name="spName"/>

              <!--parameters-->
              <xs:element name="parameters" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>

                    <!--parameter-->
                    <xs:element name="parameter" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="parameterName"/>
                          <xs:element name="spParameterName"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>

                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              
              <!--return data type-->
              <xs:element name="returnDataType">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="Enumerable"/>
                    <xs:enumeration value="Entity"/>
                    <xs:enumeration value="Scalar"/>
                    <xs:enumeration value="NoReturnValue"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              
            </xs:sequence>
            <xs:attribute name="name" use="required"/>
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ManeStepanyan/MobileStore/CatalogAPI/MapInfo/CatalogMap.xml
<?xml version="1.0" encoding="utf-8" ?>
<operations
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="MapSchema.xsd">
  <operation name="GetAllProducts">
    <spName>GetProducts</spName>
    <returnDataType>Enumerable</returnDataType>
  </operation>
  <operation name='GetProduct'>
    <spName>GetProductById</spName>
    <parameters>
      <parameter>
        <parameterName>id</parameterName>
        <spParameterName>Id</spParameterName>
      </parameter>
    </parameters>
    <returnDataType>Entity</returnDataType>
  </operation>
  <operation name='GetProductByName'>
    <spName>GetProductByName</spName>
    <parameters>
      <parameter>
        <parameterName>name</parameterName>
        <spParameterName>Name</spParameterName>
      </parameter>
    </parameters>
    <returnDataType>Entity</returnDataType>
  </operation>
</operations>

=== ManeStepanyan/MobileStore/OrdersAndShopCartApi/MapInfo/OrdersAndShopCartMap.xml
<?xml version="1.0" encoding="utf-8" ?>
<operations
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="MapSchema.xsd">
  <operation name="GetAllOrders">
    <spName>GetAllOrders</spName>
    <returnDataType>Enumerable</returnDataType>
  </operation>
  <operation name='GetOrderById'>
    <spName>GetOrderByOrderId</spName>
    <parameters>
      <parameter>
        <parameterName>id</parameterName>
        <spParameterName>Id</spParameterName>
      </parameter>
    </parameters>
    <returnDataType>Entity</returnDataType>
  </operation>
  <operation name='GetOrderByTimeSpan'>
    <spName>GetOrderByTimeSpan</spName>
    <parameters>
      <parameter>
        <parameterName>start</parameterName>
        <spParameterName>start</spParameterName>
      </parameter>
      <parameter>
        <parameterName>end</parameterName>
        <spParameterName>end</spParameterName>
      </parameter>
    </parameters>
    <returnDataType>Entity</returnDataType>
  </operation>
  <operation name='GetOrderByProductId'>
    <spName>GetOrderByOrderId</spName>
    <parameters>
      <parameter>
        <parameterName>id</parameterName>
        <spParameterName>Id</spParameterName>
      </parameter>
    </parameters>
    <returnDataType>Entity</returnDataType>
  </operation>
  <operation name='CreateOrder'>
    <spName>CreateOrder</spName>
    <parameters>
      <parameter>
        <parameterName>ProductId</parameterName>
        <spParameterName>ProductId</spParameterName>
      </parameter>
      <parameter>
        <parameterName>Date</parameterName>
        <spParameterName>Date</spParameterName>
      </parameter>
      <parameter>
        <parameterName>version</parameterName>
        <spParameterName>Version</spParameterName>
      </parameter>
      <parameter>
        <parameterName>Address</parameterName>
        <spParameterName>Address</spParameterName>
      </parameter>
      <parameter>
        <parameterName>CellPhone</parameterName>
        <spParameterName>CellPhone</spParameterName>
      </parameter>
      <parameter>
        <parameterName>Quantity</parameterName>
        <spParameterName>Quantity</spParameterName>
      </parameter>
      <parameter>
        <parameterName>TotalAmount</parameterName>
        <spParameterName>TotalAmount</spParameterName>
      </parameter>
    </parameters>
    <returnDataType>Scalar</returnDataType>
  </operation>
  <operation name='DeleteOrder'>
    <spName>DeleteOrder</spName>
    <parameters>
      <parameter>
        <parameterName>id</parameterName>
        <spParameterName>Id</spParameterName>
      </parameter>
    </parameters>
    <returnDataType>NoReturnData</returnDataType>
  </operation>
  <operation name="GetAllShopCarts">
    <spName>GetAllShopCarts</spName>
    <returnDataType>Enumerable</returnDataType>
  </operation>
  <operation name='GetShopCartById'>
    <spName>GetShopCartById</spName>
    <parameters>
      <parameter>
        <parameterName>id</parameterName>
        <spParameterName>Id</spParameterName>
      </parameter>
    </parameters>
    <returnDataType>Entity</returnDataType>
  </operation>
   <operation name='AddToShopCart'>
    <spName>AddToShopCart</spName>
    <parameters>
      <parameter>
        <parameterName>CostumerId</parameterName>
        <spParameterName>Customer_Id</spParameterName>
      </parameter>
      <parameter>
        <parameterName>ProductId</parameterName>
        <spParameterName>Product_Id</spParameterName>
      </parameter>
      <parameter>
        <parameterName>Quantity</parameterName>
        <spParameterName>Quantity</spParameterName>
      </parameter>
    </parameters>
    <returnDataType>Scalar</returnDataType>
  </operation>
  <operation name='UpdateShopCart'>
    <spName>UpdateShopCart</spName>
    <parameters>
      <parameter>
        <parameterName>id</parameterName>
        <spParameterName>Id</spParameterName>
      </parameter>
      <parameter>
        <parameterName>quantity</parameterName>
        <spParameterName>Quantity</spParameterName>
      </parameter>
    </parameters>
    <returnDataType>Scalar</returnDataType>
  </operation>
  <operation name='DeleteFromShopCart'>
    <spName>DeleteFromShopCart</spName>
    <parameters>
      <parameter>
        <parameterName>id</parameterName>
        <spParameterName>Id</spParameterName>
      </parameter>
    </parameters>
    <returnDataType>NoReturnData</returnDataType>
  </operation>
</operations>

=== ManeStepanyan/MobileStore/CatalogAPI/CatalogMap.xml
<?xml version="1.0" encoding="utf-8" ?>
<operations>
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="MapSchema.xsd">
  <operation name="AddSellerProduct">
    <spName>AddSellerProduct</spName>
    <parameters>
      <parameter>
        <parameterName>productId</parameterName>
        <spParameterName>Product_Id</spParameterName>
      </parameter>
      <parameter>
        <parameterName>sellerId</parameterName>
        <spParameterName>Seller_Id</spParameterName>
      </parameter>
    </parameters>
    <returnDataType>NoReturnValue</returnDataType>
  </operation>
</operations>

=== ManeStepanyan/MobileStore/ProductAPI/ProductMap.xml
<?xml version="1.0" encoding="utf-8" ?>
<operations
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="MapSchema.xsd">
  <operation name='CreateProduct'>
    <spName>CreateProduct</spName>
    <parameters>
      <parameter>
        <parameterName>name</parameterName>
        <spParameterName>Name</spParameterName>
      </parameter>
          <parameter>
        <parameterName>brand</parameterName>
        <spParameterName>Brand</spParameterName>
      </parameter>
              <parameter>
        <parameterName>version</parameterName>
        <spParameterName>Version</spParameterName>
      </parameter>
              <parameter>
        <parameterName>price</parameterName>
        <spParameterName>Price</spParameterName>
      </parameter>
                <parameter>
        <parameterName>ram</parameterName>
        <spParameterName>RAM</spParameterName>
      </parameter>
            <parameter>
        <parameterName>year</parameterName>
        <spParameterName>Year</spParameterName>
      </parameter>
              <parameter>
        <parameterName>display</parameterName>
        <spParameterName>Display</spParameterName>
      </parameter>
      <parameter>
      <parameterName>battery</parameterName>
        <spParameterName>Battery</spParameterName>
      </parameter>
     <parameter>
      <parameterName>camera</parameterName>
        <spParameterName>Camera</spParameterName>
      </parameter>
     <parameter>
      <parameterName>image</parameterName>
        <spParameterName>Image</spParameterName>
      </parameter>
    </parameters>
    <returnDataType>Scalar</returnDataType>
  </operation>
  <operation name="GetAllProducts">
    <spName>GetAllProducts</spName>
    <returnDataType>Enumerable</returnDataType>
  </operation>
  <operation name='GetProduct'>
    <spName>GetProductById</spName>
    <parameters>
      <parameter>
        <parameterName>id</parameterName>
        <spParameterName>Id</spParameterName>
      </parameter>
    </parameters>
    <returnDataType>Enumerable</returnDataType>
  </operation>
  <operation name='GetProductByName'>
    <spName>GetProductByName</spName>
    <parameters>
      <parameter>
        <parameterName>name</parameterName>
        <spParameterName>Name</spParameterName>
      </parameter>
    </parameters>
    <returnDataType>Entity</returnDataType>
  </operation>
  <operation name='DeleteProduct'>
    <spName>DeleteProduct</spName>
    <parameters>
      <parameter>
        <parameterName>id</parameterName>
        <spParameterName>Id</spParameterName>
      </parameter>
    </parameters>
    <returnDataType>NoReturnData</returnDataType>
  </operation>
  <operation name='UpdateProduct'>
    <spName>UpdateProduct</spName>
    <parameters>
      <parameter>
        <parameterName>price</parameterName>
        <spParameterName>Price</spParameterName>
      </parameter>
      <parameter>
        <parameterName>image</parameterName>
        <spParameterName>Image</spParameterName>
      </parameter>
    </parameters>
    <returnDataType>NoReturnValue</returnDataType>
  </operation>
 <operation name='SearchProduct'>
    <spName>SearchProduct</spName>
   <parameters>
     <parameter>
       <parameterName>name</parameterName>
       <spParameterName>Name</spParameterName>
     </parameter>
     <parameter>
       <parameterName>brand</parameterName>
       <spParameterName>Brand</spParameterName>
     </parameter>
     <parameter>
       <parameterName>version</parameterName>
       <spParameterName>Version</spParameterName>
     </parameter>
     <parameter>
       <parameterName>price</parameterName>
       <spParameterName>Price</spParameterName>
     </parameter>
     <parameter>
       <parameterName>ram</parameterName>
       <spParameterName>RAM</spParameterName>
     </parameter>
     <parameter>
       <parameterName>year</parameterName>
       <spParameterName>Year</spParameterName>
     </parameter>
     <parameter>
       <parameterName>display</parameterName>
       <spParameterName>Display</spParameterName>
     </parameter>
     <parameter>
       <parameterName>battery</parameterName>
       <spParameterName>Battery</spParameterName>
     </parameter>
     <parameter>
       <parameterName>camera</parameterName>
       <spParameterName>Camera</spParameterName>
     </parameter>
     <parameter>
       <parameterName>image</parameterName>
       <spParameterName>Image</spParameterName>
     </parameter>
   </parameters>
    <returnDataType>Enumerable</returnDataType>
  </operation>
</operations>
